### ISSUE TITLE
View docs when cloud run service is on a custom domain

### ISSUE THREAD

**Issue by ydennisy** [anthonycorletti/cloudrun-fastapi#16]
Hi! Thanks for this repo.

Quick q, I am able to view docs on the raw cloud run domain, but I am using a custom domain mapping so all my services are reachable at `customdomain.com/{service-name}`, this works fine for all uses apart from the docs are not available at `customdomain.com/{service-name}/docs`

Any idea why that could be the case?

**Comment by anthcor** [comment]
Hi @ydennisy, unfortunately I don't know exactly what the problem is without knowing more about your setup. I do have a hunch though; because you are deploying your service to `hostname/my-fastapi` your docs might not work because locally they expect `hostname/docs` and not `hostname/fastapi/docs`. Maybe try configuring the docs url to see if that helps? https://fastapi.tiangolo.com/tutorial/metadata/?h=docs#docs-urls
